lattice_name: b5p40kp119989kp119812
momdict:
    "op8_q+4+4+0_op8_q-4-4+0": 
      - [-2, -2, 0]
      - [2, 2, 0]
    "op2_q+4+4+0_op2_q-4-4+0": 
      - [-2, -2, 0]
      - [2, 2, 0]
    "op8_q+4+2+0_op8_q-4-2+0": 
      - [-2, -1, 0]
      - [2, 1, 0]
    "op2_q+4+2+0_op2_q-4-2+0": 
      - [-2, -1, 0]
      - [2, 1, 0]
    "op8_q+2+2+2_op8_q-2-2-2":
      - [-1, -1, -1]
      - [1, 1, 1]
    "op2_q+2+2+2_op2_q-2-2-2":
      - [-1, -1, -1]
      - [1, 1, 1]
    "op8_q+2+0+0_op8_q-2+0+0": 
      - [-1, 0, 0]
      - [1, 0, 0]
    "op2_q+2+0+0_op2_q-2+0+0": 
      - [-1, 0, 0]
      - [1, 0, 0]
    "op8_q+0+0+0": 
      - [0, 0, 0]
    "": 
      - [-2, -2, 0]
      - [2, 2, 0]
      - [-2, -1, 0]
      - [2, 1, 0]
      - [-1, -1, -1]
      - [1, 1, 1]
      - [-1, 0, 0]
      - [1, 0, 0]
      - [0, 0, 0]
filenamelist: [ "b5p40kp119989kp119812_200.lst" ]
filenamelist_meson: [ "b5p40kp119989kp119812_meson.lst"]
savelocation: "/scratch/usr/hhpmbate/pickle_files/b5p40kp119989kp119812/"

