lattice_name: b5p50kp120900kp120900
momdict:
  "p+0+0+0" :
     - [0, 0, 0]
     - [1, 0, 0]
filenamelist: [ "bar3ptfn_t13_U.lst", "bar3ptfn_t13_D.lst"]
savelocation: "/scratch/e31/mb6847/phoenixdata/b5p50kp120900kp120900_t13/pickle2/"
