lattice_name: b5p80kp122880kp122670
momdict:
    "op8_q+6+4+2_op8_q-6-4-2": 
      - [-3, -2, -1]
      - [3, 2, 1]
    "op2_q+6+4+2_op2_q-6-4-2": 
      - [-3, -2, -1]
      - [3, 2, 1]
    "op8_q+6+0+0_op8_q-6+0+0": 
      - [-3, 0, 0]
      - [3, 0, 0]
    "op2_q+6+0+0_op2_q-6+0+0": 
      - [-3, 0, 0]
      - [3, 0, 0]
    "op8_q+4+4+2_op8_q-4-4-2": 
      - [-2, -2, -1]
      - [2, 2, 1]
    "op2_q+4+4+2_op2_q-4-4-2": 
      - [-2, -2, -1]
      - [2, 2, 1]
    "op8_q+4+2+2_op8_q-4-2-2": 
      - [-2, -1, -1]
      - [2, 1, 1]
    "op2_q+4+2+2_op2_q-4-2-2": 
      - [-2, -1, -1]
      - [2, 1, 1]
    "op8_q+2+2+0_op8_q-2-2+0":
      - [-1, -1, 0]
      - [1, 1, 0]
    "op2_q+2+2+0_op2_q-2-2+0": 
      - [-1, -1, 0]
      - [1, 1, 0]
    "op8_q+0+0+0_op8_q+0+0+0": 
      - [0, 0, 0]
    "": 
      - [-3, -2, -1]
      - [3, 2, 1]
      - [-3, 0, 0]
      - [3, 0, 0]
      - [-2, -2, -1]
      - [2, 2, 1]
      - [-2, -1, -1]
      - [2, 1, 1]
      - [-1, -1, 0]
      - [1, 1, 0]
      - [0, 0, 0]
filenamelist: [ "b5p80kp122880kp122670.lst"]
filenamelist_meson: [ "b5p80kp122880kp122670_meson_642.lst", "b5p80kp122880kp122670_meson_no642.lst"]
savelocation: "/scratch/usr/hhpmbate/pickle_files/b5p80kp122880kp122670/"

