#!/bin/bash
#SBATCH -t 12:00:00
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --tasks-per-node 1
#SBATCH -p large96
#SBATCH -A hhp00045
#SBATCH -J picklelime

# run job
umask 022

start_time=$(date +%M)
echo "job start date: $(date)"

module load anaconda3/2019.10

# python -u unpack_mesons.py b5p80kp122880kp122670 > messpec_job2.out
python -u unpack_mesons.py b5p80kp122940kp122551 > messpec_job3.out

end_time=$(date +%M)
echo "job end date: $(date)"

#-------------------------------------------------------------------------------

