#!/bin/bash
#SBATCH -t 12:00:00
#SBATCH -N 1
#SBATCH --ntasks=1
#SBATCH --tasks-per-node 1
#SBATCH -p standard96
#SBATCH -A hhp00045
#SBATCH -J pickle_barspec

# run job
umask 022

start_time=$(date +%M)
echo "job start date: $(date)"

module load anaconda3/2019.10

# python -u unpack_FH.py b5p80kp122810kp122810 > barspec_job.out
# python -u unpack_FH.py b5p80kp122810kp122810_src2 > barspec_job.out
# python -u unpack_FH.py b5p80kp122880kp122670 > barspec_job2.out
# python -u unpack_FH.py b5p80kp122940kp122551 > barspec_job3.out
# python -u unpack_FH.py b5p40kp119989kp119812 > barspec_job4.out

# python -u unpack_FH.py b5p40kp119989kp119812_000 > barspec_job000.out
# python -u unpack_FH.py b5p40kp119989kp119812_200 > barspec_job200.out
# python -u unpack_FH.py b5p40kp119989kp119812_222 > barspec_job222.out
# python -u unpack_FH.py b5p40kp119989kp119812_420 > barspec_job420.out
# python -u unpack_FH.py b5p40kp119989kp119812_440 > barspec_job440.out

python -u unpack_FH.py b5p40kp119989kp119812_src2_000 > barspec_job000_src2.out
python -u unpack_FH.py b5p40kp119989kp119812_src2_200 > barspec_job200_src2.out
python -u unpack_FH.py b5p40kp119989kp119812_src2_222 > barspec_job222_src2.out
python -u unpack_FH.py b5p40kp119989kp119812_src2_420 > barspec_job420_src2.out
python -u unpack_FH.py b5p40kp119989kp119812_src2_440 > barspec_job440_src2.out

end_time=$(date +%M)
echo "job end date: $(date)"

#-------------------------------------------------------------------------------

